language: node_js
node_js:
  - '12'
cache: yarn
install:
  - yarn install
script:
  - yarn lint
after_success:
  - if [ "$TRAVIS_BRANCH" = "v3.1" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn build-doc; fi
  - if [ "$TRAVIS_BRANCH" = "v3.1" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash travis-push.sh; fi
